Improve user management for `Xray-core`

diff --git a/xray/Dockerfile b/xray/Dockerfile
--- a/xray/Dockerfile
+++ b/xray/Dockerfile
@@ -29,6 +29,20 @@ RUN apt-get update && \
     apt-get -y autoremove; \
     apt-get clean; \
     #
+    script=/usr/local/bin/xray-user; \
+    echo '#!/usr/bin/env bash' > $script; \
+    echo 'username=$(echo $2 | tr "[:upper:]" "[:lower:]")' >> $script; \
+    echo '[[ $username = *[[:space:]]* ]] && echo "Invalid username!" && exit 1' >> $script; \
+    echo 'if [ $1 = "add" ]; then' >> $script; \
+    echo '    grep -q " $username\$" /xray/password && echo "Username already exist!" && exit 1' >> $script; \
+    echo '    uuid=$(xray uuid)' >> $script; \
+    echo '    echo "$uuid $username" >> /xray/password' >> $script; \
+    echo '    echo $uuid' >> $script; \
+    echo 'elif [ $1 = "delete" ]; then' >> $script; \
+    echo '    sed -i "/ $username\$/d" /xray/password' >> $script; \
+    echo 'fi' >> $script; \
+    chmod +x $script; \
+    #
     useradd --gid proxy xray; \
     echo 'xray ALL=(root) NOPASSWD: /usr/sbin/iptables, /usr/sbin/ip6tables' >> /etc/sudoers;
 
@@ -91,20 +105,24 @@ CMD \
     clients_ws=""; \
     readarray -t passwords < /var/run/secrets/password; \
     if [ ! -z "${passwords}" ]; then \
-        for password in "${passwords[@]}"; do \
-            clients_tcp+="{\"flow\": \"xtls-rprx-vision\",\"id\": \"$password\"},"; \
-            if [[ $ENABLE_XRAY_CDN == 'true' ]]; then \
-                clients_ws+="{\"flow\": null,\"id\": \"$password\"},"; \
-            fi; \
-            if [[ $ENABLE_XRAY_SUBSCRIPTION == 'true' ]]; then \
-                echo "$password $password;" >> /tmp/xray/uuids; \
+        for line in "${passwords[@]}"; do \
+            if [ ! -z "${line// }" ]; then \
+                line=($line); \
+                shared="\"email\": \"${line[1]}@$DOMAIN\",\"id\": \"${line[0]}\""; \
+                clients_tcp+="{\"flow\": \"xtls-rprx-vision\",$shared},"; \
+                if [[ $ENABLE_XRAY_CDN == 'true' ]]; then \
+                    clients_ws+="{\"flow\": null,$shared},"; \
+                fi; \
+                if [[ $ENABLE_XRAY_SUBSCRIPTION == 'true' ]]; then \
+                    echo "${line[0]} ${line[0]};" >> /tmp/xray/uuids; \
+                fi; \
             fi; \
         done; \
         [[ $ENABLE_XRAY_CDN != 'true' ]] && clients_ws=','; \
         jq ".inbounds[0].settings.clients += [${clients_tcp::-1}] | \
             .inbounds[1].settings.clients += [${clients_ws::-1}]" \
             /usr/local/etc/xray/xray.json > /tmp/xray/xray.json; \
-        unset passwords clients_tcp clients_ws; \
+        unset passwords line shared clients_tcp clients_ws; \
     else \
         cp -f /usr/local/etc/xray/xray.json /tmp/xray/xray.json; \
     fi; \
